### ISSUE TITLE
Create a version that merge react-sdk and js-sdk to v1.2.0

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/matrix-react-sdk#369]
Goal : try to get reactions and actions in v2, and not too many bugs.

Instead of adding PRs one by one (which gives a half-broken result), try to update react-sdk and js-sdk to 1.2.0, which contain the reactions and actions. 
https://github.com/matrix-org/matrix-react-sdk/releases/tag/v1.2.0
https://github.com/matrix-org/matrix-js-sdk/releases/tag/v1.2.0

**Comment by estellecomment** [comment]
Finally we used 1.2.1
PR : #370
