### ISSUE TITLE
Improve export keys flow

### ISSUE THREAD

**Issue by celiacheff** [tchapgouv/matrix-react-sdk#398]

**Comment by Caroline-lawson** [comment]
![image](https://user-images.githubusercontent.com/78041311/167601161-60e0f297-3682-462e-b3e1-18f77221e163.png)

1. Dans le 1er paragraphe, remplacer : "**Sans vos Clés Tchap (clés de chiffrement), vous ne pourrez pas lire vos messages** à votre prochaine connexion parce qu'ils seront verrouillés. C'est une mesure de sécurité Tchap.”
par : "En vous déconnectant, **vous perdez vos Clés Tchap (clés de chiffrement) sans lequelles vous ne pourrez pas lire vos messages** chiffrés à votre prochaine connexion parce qu'ils seront verrouillés. 
C'est une mesure de sécurité Tchap. Pourquoi ?”
où "Pourquoi" est un lien vers [https://tchap.beta.gouv.fr/faq#tcq05_001].

2. Dans le 1er encart, remplacer : “Cet autre appareil sauvegarde automatiquement vos Clés Tchap et vos messages.”
par “Cet autre appareil sauvegarde automatiquement vos Clés Tchap et tous vos messages.”.

3. Dans le 2e encart, remplacer : "Ces clés déverrouilleront les messages actuels, mais pas ceux reçus après la sauvegarde."
par : "Ces clés déverrouilleront les messages actuels, mais pas ceux reçus entre cette sauvegarde et votre prochaine connexion.".

![image](https://user-images.githubusercontent.com/78041311/167614177-2aaceaa1-df9e-457e-a630-3536dec71263.png)

4. Dans le 3e paragraphe, remplacer : "Les messages reçus après cette sauvegarde ne pourront pas être déverrouillés."
par : "Les messages reçus entre cette sauvegarde et votre prochaine connexion ne pourront pas être déverrouillés.".

5. Au 1er champ, remplacer "characters"" par "caractères".

![image](https://user-images.githubusercontent.com/78041311/167615418-e04828e4-2d21-42fe-8b12-d6668b312ae9.png)

6. Remplacer le 1er paragraphe : "**Vos Clés Tchap (clés de chiffrement) ont été sauvegardées avec succès.**"
par : "**Vos Clés Tchap (clés de chiffrement) ont été sauvegardées avec succès** dans votre dossier de téléchargement habituel. Elles sont dans un fichier qui s'appelle “tchap-keys-export.”.

7. Remplacer le 2e paragraphe : "Vous pourrez les importer à votre prochaine connexion pour déverrouiller vos messages."
par : "Vous pourrez importer ce fichier à votre prochaine connexion pour déverrouiller vos messages."

8. Remplacer le dernier paragraphe : Les messages reçus après cette sauvegarde ne pourront pas déverrouillés. Vous ne pourrez donc pas les lire."
par : "Les messages reçus entre maintenant et votre prochaine connexion ne seront pas déverrouillés. Vous ne pourrez donc pas les lire."

![image](https://user-images.githubusercontent.com/78041311/167618039-15a9c007-56ae-4efd-a0a8-fbd5ee1fc5bd.png)

9. Remplacer "Importer depuis un fichier"
par "Importer depuis le fichier sauvegardé"

10. Remplacer "Messages verrouillés par sécurité" par "Message verrouillé par sécurité".

11. Afficher chaque lien sur une ligne différente.

![image](https://user-images.githubusercontent.com/78041311/167619061-42307100-62d6-4ea4-af5b-9ce9feead19d.png)

12. Dans la bulle info, remplacer : "Les demandes de partage de clé sont envoyées à vos autres appareils automatiquement. Si vous rejetez ou supprimez la demande de partage de clé sur vos autres appareils, cliquez ici pour redemander les clés. / Si vos autres appareils n'ont pas la clé pour ce message, vous ne pourrez pas le déchiffrer."
par : "Les demandes de partage de vos Clés Tchap sont automatiquement envoyées à vos autres appareils. Si vous rejetez ou supprimez la demande de partage de clé sur vos autres appareils, cliquez ici pour redemander vos Clés Tchap. / Si vos autres appareils n'ont pas la clé pour ce message, vous ne pourrez pas le déchiffrer."

![image](https://user-images.githubusercontent.com/78041311/167620188-0c9cd011-d107-4811-81bc-a47e5455527e.png)

13. Ajouter dans le titre "'clés de chiffrement)".

14. Enlever dans le texte "(clés de chiffrement)".

15. Remplacer : "Fichier à importer"
par : "**1. Choisissez le fichier contenant vos Clés Tchap.** 
Ce fichier est sauvegardé dans le dossier de vos téléchargements habituels, sauf si vous l’avez déplacé.
Ce fichier s’appelle “tchap-keys-export”, sauf si vous l’avez renommé."

16. Remplacer : "Saisissez votre mot de passe du fichier pour vos Clés Tchap :"
par : "**2. Saisissez votre mot de passe** pour vos Clés Tchap :

**Comment by Caroline-lawson** [comment]
Je ne trouve pas Angelo pour l'assigner aussi
